base/core/urls.py
from django.urls import path
from .views import (
    home,
    detail,
    category,
    about,
    contact,
    success,
)

app_name = 'core'
urlpatterns = [
    path('', home, name='home'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('category/', category, name='category'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('success/', success, name='success'),
]

base/sheeblogs/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from core.views import markdown_uploader

urlpatterns = [
    path('admin/', admin.site.urls),
    path('martor/', include('martor.urls')),
    path('api/uploader/', markdown_uploader, name='markdown_uploader_page'),
    path('', include('core.urls', namespace='core')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/core/models.py
from django.db import models
from martor.models import MartorField


class Author(models.Model):
    author_name = models.CharField(max_length=50)
    author_email = models.EmailField()
    author_intro = models.CharField(max_length=300)
    author_bio = models.TextField()
    author_image = models.ImageField()

    def __str__(self):
        return self.author_name


class Category(models.Model):
    blog_category = models.CharField(max_length=100)

    def __str__(self):
        return self.blog_category


class Entry(models.Model):
    blog_image = models.ImageField(null=True)
    title = models.CharField(max_length=100)
    tagline = models.CharField(max_length=300)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    body_text = MartorField()
    pub_date = models.DateTimeField(auto_now_add=True)
    mod_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    no_of_comments = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Comment(models.Model):
    author = models.CharField(max_length=20)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    blog = models.ForeignKey('Entry', on_delete=models.CASCADE)

    def __str__(self):
        return self.author

base/core/forms.py
from django import forms
from martor.fields import MartorFormField

class CommentForm(forms.Form):
	author = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'Name',
	}))
	email = forms.EmailField(required=True, widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'Email',
	}))
	body = forms.CharField(max_length=200, required=True, widget=forms.Textarea(attrs={
		"rows": "5",
		"class": "form-control",
		"id": "message",
		"placeholder": "Message"
	}))


class ContactForm(forms.Form):
	name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'Name',
	}))
	email = forms.EmailField(required=True, widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'Email',
	}))
	subject = forms.CharField(required=True, widget=forms.TextInput(attrs={
		'class': 'form-control',
		'placeholder': 'Subject',
	}))
	message = forms.CharField(max_length=200, required=True, widget=forms.Textarea(attrs={
		"rows": "10",
		"class": "form-control",
		"id": "message",
		"placeholder": "Message"
	}))

base/core/views.py
import os
import json
import uuid

from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.shortcuts import render, redirect
from django.core.mail import send_mail, BadHeaderError

from martor.utils import LazyEncoder

from .models import Entry, Category, Comment
from .forms import CommentForm, ContactForm


def home(request):
    blogs = Entry.objects.all()
    return render(request, 'index.html', {'blogs': blogs})


def category(request, category):
    blogs = Entry.objects.filter(categories__name__contains=category)
    return render(request, 'index.html', {'blogs': blogs})


def detail(request, pk):
    entry = Entry.objects.get(pk=pk)
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author=form.cleaned_data["author"],
                email=form.cleaned_data["email"],
                body=form.cleaned_data["body"],
                blog=entry
            )
            comment.save()
            entry.no_of_comments += 1
            entry.save()
    comments = Comment.objects.filter(blog=entry)
    return render(request, 'detail.html', {'entry': entry, 'comments': comments, 'form': form})


def contact(request):
    if request.method == 'GET':
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email,
                          ['armarmaanmalik@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('core:success')
    return render(request, "contact.html", {'form': form})


def success(request):
    context = {}
    return render(request, "success.html", context)


def about(request):
    context = {}
    return render(request, "about.html", context)



@login_required
def markdown_uploader(request):
    """
    Makdown image upload for locale storage
    and represent as json to markdown editor.
    """
    if request.method == 'POST' and request.is_ajax():
        if 'markdown-image-upload' in request.FILES:
            image = request.FILES['markdown-image-upload']
            image_types = [
                'image/png', 'image/jpg',
                'image/jpeg', 'image/pjpeg', 'image/gif'
            ]
            if image.content_type not in image_types:
                data = json.dumps({
                    'status': 405,
                    'error': _('Bad image format.')
                }, cls=LazyEncoder)
                return HttpResponse(
                    data, content_type='application/json', status=405)

            if image.size > settings.MAX_IMAGE_UPLOAD_SIZE:
                to_MB = settings.MAX_IMAGE_UPLOAD_SIZE / (1024 * 1024)
                data = json.dumps({
                    'status': 405,
                    'error': _('Maximum image file is %(size) MB.') % {'size': to_MB}
                }, cls=LazyEncoder)
                return HttpResponse(
                    data, content_type='application/json', status=405)

            img_uuid = "{0}-{1}".format(
                uuid.uuid4().hex[:10], image.name.replace(' ', '-'))
            tmp_file = os.path.join(settings.MARTOR_UPLOAD_PATH, img_uuid)
            def_path = default_storage.save(
                tmp_file, ContentFile(image.read()))
            img_url = os.path.join(settings.MEDIA_URL, def_path)

            data = json.dumps({
                'status': 200,
                'link': img_url,
                'name': image.name
            })
            return HttpResponse(data, content_type='application/json')
        return HttpResponse(_('Invalid request!'))
    return HttpResponse(_('Invalid request!'))

base/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<!-- About Section -->

<section id="about">
     <div class="container">
          <div class="row">
               <div class="col-md-12">
                    <h3>Who I am</h3>

                    <p>Maecenas quis pulvinar neque, non dapibus orci. Integer non suscipit dui. In eu tempor
                         sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                         turpis egestas. Cras porta lacus ac sagittis imperdiet. Vestibulum eget mattis quam.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                         labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita.</p>

                    <hr>

                    <img src="{% static 'images/about-image.jpg' %}" class="img-responsive" alt="About Image">

                    <hr>

                    <h3>One Column</h3>
                    <br>
                    <p>Maecenas quis pulvinar neque, non dapibus orci. Integer non suscipit dui. In eu tempor
                         sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                         turpis egestas. Cras porta lacus ac sagittis imperdiet. Vestibulum eget mattis quam.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                         labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita.</p>
                    <p>Maecenas quis pulvinar neque, non dapibus orci. Integer non suscipit dui. In eu tempor
                         sapien. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac
                         turpis egestas. Cras porta lacus ac sagittis imperdiet. Vestibulum eget mattis quam.</p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
                         labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercita.</p>
     
               </div>
          </div>
     </div>
</section>

{% endblock content  %}

base/templates/base.html
<!DOCTYPE html> {% load static %}
<html lang="en">

<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <title>BlogReally</title>
    <!--

    Template 2085 Neuron

    http://www.tooplate.com/view/2085-neuron

    -->

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Voltaire" rel="stylesheet">

</head>

<body>
    <div class="preloader">
        <div class="sk-spinner sk-spinner-wordpress">
            <span class="sk-inner-circle"></span>
        </div>
    </div>
    {% include 'navbar.html' %} {% block content %} {% endblock content %}

    <a href="#back-top" class="go-top"><i class="fa fa-angle-up"></i></a> {% include 'footer.html' %} {% include 'scripts.html' %}
</body>

</html>

base/templates/contact.html
{% extends "base.html" %} {% block content %}

<!-- Contact Section -->

<section id="contact">
    <div class="container">
        <div class="row">

            <div class="col-md-offset-1 col-md-10 col-sm-12">
                <h2>Say hello..</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis
                    aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>

                <!-- <form action="#" method="post">
                    <div class="col-md-4 col-sm-4">
                        <input name="name" type="text" class="form-control" id="name" placeholder="Name">
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <input name="email" type="email" class="form-control" id="email" placeholder="Email">
                    </div>
                    <div class="col-md-4 col-sm-4">
                        <input name="subject" type="text" class="form-control" id="subject" placeholder="Subject">
                    </div>
                    <div class="col-md-12 col-sm-12">
                        <textarea name="message" rows="5" class="form-control" id="message" placeholder="Message"></textarea>
                    </div>
                    <div class="col-md-3 col-sm-6">
                        <input name="submit" type="submit" class="form-control" id="submit" value="Send">
                    </div>
                </form> -->

                <form action="/contact/" method='post'>
                    {% csrf_token %}
                    <div>{{form.name}}</div>
                    <div>{{form.email}}</div>
                    <div>{{form.subject}}</div>
                    <div>{{form.message}}</div>
                    <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
                    <div class="col-md-3 col-sm-6">
                        <input name="submit" type="submit" class="form-control" id="submit" value="Send">
                    </div>
                </form>

            </div>

        </div>
    </div>
</section>


{% endblock %}

base/templates/detail.html
{% extends "base.html" %} {% load static %} {% load martortags %} {% block content %}

<section id="blog-single-post">
    <div class="container">
        <div class="row">
            <div class="col-md-offset-1 col-md-10 col-sm-12">
                <div class="blog-single-post-thumb">

                    <div class="blog-post-title">
                        <h2>{{ entry.title }}</h2>
                    </div>
                    <div class="blog-post-format">
                        <span><a href="#"><img src="{{ entry.author.author_image.url }}"
                                             class="img-responsive img-circle"> {{ entry.author.name }} </a></span>
                        <span><i class="fa fa-date"></i>{{ entry.pub_date }}</span>
                        <span><a href="#blog-comment"><i class="fa fa-comment-o"></i> {{ entry.no_of_comments }}
                                        Comments</a></span>
                    </div>

                    <div class="blog-post-des">
                        {{ entry.body_text|safe_markdown }}
                    </div>

                    <div class="blog-author">
                        <div class="media">
                            <div class="media-object pull-left">
                                <img src="{{ entry.author.author_image.url }}" class="img-circle img-responsive" alt="image">
                            </div>
                            <div class="media-body">
                                <h3 class="media-heading"><a href="#">{{ entry.author.author_name }}</a></h3>
                                <p>{{ entry.author.author_intro }}</p>
                            </div>
                        </div>
                    </div>

                    <div class="blog-comment" id="blog-comment">
                        <h3>Comments</h3>
                        {% if comments %} {% for comment in comments %}
                        <div class="media">
                            <!-- <div class="media-object pull-left">
                                             <img src="{% static 'images/comment-image1.jpg' %}" class="img-responsive img-circle" alt="Blog Image 11">
                                        </div> -->
                            <div class="media-body">
                                <h3 class="media-heading">{{ comment.author }}</h3>
                                <span>{{ comment.created_on }}</span>
                                <p>{{comment.body}}</p>
                            </div>
                        </div>
                        {% endfor %} {% endif %}
                    </div>

                    <div class="blog-comment-form">
                        <h3>Leave a Comment</h3>
                        <form action="/detail/{{entry.id}}/" method='post'>
                            {% csrf_token %}
                            <div>
                                {{form.author}}
                            </div>
                            <div>
                                {{form.email}}
                            </div>
                            <div>
                                {{form.body}}
                            </div>
                            <!-- <button type="submit" class="btn btn-primary">Submit</button> -->
                            <div class="col-md-3 col-sm-4">
                                <input name="submit" type="submit" class="form-control" id="submit" value="Post Your Comment">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

base/templates/footer.html
{% load static %}

<footer>
    <div class="container">
        <div class="row">

            <div class="col-md-12">
                <div class="footer-copyright text-center">
                    <p>Copyright &copy; 2020 BlogReally - Template Design By: <a href="https://www.tooplate.com/view/2085-neuron">Tooplate</a> </p>
                </div>
            </div>

            <div class="clearfix col-md-12 col-sm-12">
                <hr>
            </div>

            <div class="col-md-12">
                <ul class="social-icon">
                    <li>
                        <a href="#" class="fa fa-facebook"></a>
                    </li>
                    <li>
                        <a href="#" class="fa fa-twitter"></a>
                    </li>
                    <li>
                        <a href="#" class="fa fa-instagram"></a>
                    </li>
                </ul>
            </div>

        </div>
    </div>
</footer>

base/templates/index.html
{% extends "base.html" %} {% load static %} {% block content %}

<section id="home" class="main-home parallax-section">
    <div class="overlay"></div>
    <div id="particles-js"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <h1>Hello! Welcome to BlogReally</h1>
                <a href="#blog" class="smoothScroll btn btn-default">Discover More</a>
            </div>
        </div>
    </div>
</section>

<section id="blog">
    <div class="container">
        <div class="row">
            {% for blog in blogs %}
            <div class="col-md-offset-1 col-md-10 col-sm-12">
                <div class="blog-post-thumb">
                    <div class="blog-post-image">
                        <a href="{% url 'core:detail' blog.pk %}">
                            <img src="{{ blog.blog_image.url }}" class="img-responsive" alt="Blog Image">
                        </a>
                    </div>
                    <div class="blog-post-title">
                        <h3><a href="{% url 'core:detail' blog.pk %}">{{ blog.title }}</a></h3>
                    </div>
                    <div class="blog-post-format">
                        <span><a href="#"><img src="{{ blog.author.author_image.url }}" class="img-responsive img-circle" alt="image"> {{ blog.author.author_name }} </a></span>
                        <span><i class="fa fa-date"></i> {{ blog.pub_date }} </span>
                        <span><a href="{% url 'core:detail' blog.pk %}#blog-comment"><i class="fa fa-comment-o"></i> {{ blog.no_of_comments }} Comments </a></span>
                    </div>
                    <div class="blog-post-des">
                        <p>{{ blog.tagline }}</p>
                        <a href="{% url 'core:detail' blog.pk %}" class="btn btn-default">Read Blog</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock content %}

base/templates/navbar.html
{% load static %}
<nav>
    <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">

            <div class="navbar-header">
                <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                       <span class="icon icon-bar"></span>
                       <span class="icon icon-bar"></span>
                       <span class="icon icon-bar"></span>
                  </button>
                <a href="{% url 'core:home' %}" class="navbar-brand">BlogReally</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'core:home' %}">Home</a></li>
                    <li><a href="{% url 'core:about' %}">About</a></li>
                    <li><a href="{% url 'core:contact' %}">Contact</a></li>
                </ul>
            </div>

        </div>
    </div>
</nav>

base/templates/scripts.html
{% load static %}

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/particles.min.js' %}"></script>
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/jquery.parallax.js' %}"></script>
<script src="{% static 'js/smoothscroll.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>

base/templates/success.html
{% extends "base.html" %} {% block content %}

<section id="contact">
    <div class="container">
        <div class="row">

            <div class="col-md-offset-1 col-md-10 col-sm-12">
                <h2>Thank you for the message..</h2>
                <p>We will get back to you soon!</p>
            </div>

        </div>
    </div>
</section>

{% endblock %}